showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: true
showDonateUrl: false

# Default til
languageIcon: languages

# O'zbek tilini birinchi ko'rsatish
languages:
    - uz
    - en
    - ru

requirements:
    requiredStorage: 20.0
    requiredRam: 2.0
    internetCheckUrl: https://geoip.kde.org/v1/calamares
    check:
        - storage
        - ram
        - root
    required:
        - storage
        - ram
        - root
