[greeter]
background = /usr/share/backgrounds/hacknow/login.png
theme-name = HackNow-Dark
icon-theme-name = Papirus-Dark
font-name = Noto Sans 11
xft-antialias = true
xft-hintstyle = hintfull
indicators = ~host;~spacer;~clock;~spacer;~session;~language;~a11y;~power
clock-format = %H:%M | %d.%m.%Y
position = 50%,center 50%,center
panel-position = top
user-background = false
active-monitor = 0
